[build]
  publish = "."

[functions]
  directory = "netlify/functions"

# Don't serve the function source files as web pages.
[[redirects]]
  from = "/netlify/*"
  to = "/404.html"
  status = 404
  force = true
